// Classmates list — hardcoded. Sorted alphabetically by first name for display.
// Each entry has first, last, and display (computed).

const CLASSMATES = [
  { first: "Rebecca", last: "Abara-Azubuike" },
  { first: "Eyram", last: "Adedze" },
  { first: "Amanda", last: "Agyapong" },
  { first: "Kofi", last: "Agyare-Kwabi" },
  { first: "Adem", last: "Ahmed" },
  { first: "Will", last: "Ahoua" },
  { first: "Tolu", last: "Alamu" },
  { first: "Kola", last: "Alawaiye" },
  { first: "Daniele", last: "Anderson" },
  { first: "Illen", last: "Asmerom" },
  { first: "Kojoh", last: "Atta" },
  { first: "Nayo", last: "Ayegbajeje" },
  { first: "Abigael", last: "Bamgboye" },
  { first: "Lorentez", last: "Barbour" },
  { first: "Ben", last: "Barnett" },
  { first: "Olamide", last: "Bola" },
  { first: "Wynston", last: "Bouknight" },
  { first: "Kennedy", last: "Boyd" },
  { first: "Ari", last: "Brathwaite" },
  { first: "Nati", last: "Bulcho" },
  { first: "Tome", last: "Buluku" },
  { first: "Erika", last: "Chapman" },
  { first: "James", last: "Cobbinah" },
  { first: "Nia", last: "Coleman" },
  { first: "Isabella", last: "Coleman" },
  { first: "Gaelle", last: "Conille" },
  { first: "Analia", last: "Cuevas-Ferreras" },
  { first: "Allysha", last: "Davis" },
  { first: "Alexander", last: "Deaderick" },
  { first: "Hinda", last: "Diakite" },
  { first: "Brannen", last: "Dickson" },
  { first: "Blessing", last: "Edem" },
  { first: "Rowa", last: "El-tohami" },
  { first: "Terrell", last: "Estime" },
  { first: "Joshua", last: "Folarin" },
  { first: "John", last: "Franklin" },
  { first: "Elyshia", last: "Geter" },
  { first: "Allison", last: "Holmes" },
  { first: "Mueni", last: "Ithau" },
  { first: "Lamar", last: "Johnson-Harris" },
  { first: "Alexis", last: "Jones" },
  { first: "Jillian", last: "Jones" },
  { first: "Kamal", last: "Kadiri" },
  { first: "Quintin", last: "Lassiter" },
  { first: "Jose", last: "Martinez" },
  { first: "Samuel", last: "McDaniel" },
  { first: "Kenton", last: "McNeal" },
  { first: "Koyeawon", last: "Mendee" },
  { first: "Kiera", last: "Mercier-Solodar" },
  { first: "Kendese", last: "Nangle" },
  { first: "Tosa", last: "Nehikhuere" },
  { first: "Lyncy", last: "Nyandoche" },
  { first: "Lapo", last: "Odunjo" },
  { first: "Haniel", last: "Ogburu-Ogbonnaya" },
  { first: "Nkeiruka", last: "Okororie" },
  { first: "Sikemi", last: "Olumide-Fusika" },
  { first: "Islam", last: "Osman" },
  { first: "Dabila", last: "Ouattara" },
  { first: "Onyi", last: "Ozoma" },
  { first: "Makeda", last: "Petiri" },
  { first: "Brianna", last: "Plowright Gurrell" },
  { first: "Pam", last: "Poteh" },
  { first: "Morganne", last: "Ramsey" },
  { first: "Lyndon", last: "Sam" },
  { first: "Tyrone", last: "Scafe" },
  { first: "Tema", last: "Shongwe" },
  { first: "Wes", last: "Suggs" },
  { first: "Kukua", last: "Tandoh" },
  { first: "Loic", last: "Tchebetchou" },
  { first: "Alima", last: "Travaly" },
  { first: "Andrew", last: "Udofa" },
  { first: "James", last: "Walker III" },
  { first: "George", last: "Walker V" },
  { first: "Tennessee", last: "Watt" },
  { first: "Kenya", last: "Wright" },
].map(c => ({ ...c, display: `${c.first} ${c.last}` }))
  .sort((a, b) => a.first.localeCompare(b.first));
