// Superlatives list — hardcoded.
// type: "single" = one nominee, "duo" = two nominees (pair).

const SUPERLATIVES = [
  { id: "uber_everywhere", title: "The Uber Everywhere Award", description: "Anti-walking. Somehow always in a car.", type: "single" },
  { id: "silent_hustler", title: "The Silent Hustler Award", description: "Quiet grind, big impact.", type: "single" },
  { id: "social_butterfly", title: "The Social Butterfly Award", description: "Knows everyone across every circle.", type: "single" },
  { id: "soft_life_ceo", title: "The Soft Life CEO Award", description: "Found the balance at Wharton that we all aspire to.", type: "single" },
  { id: "linkedin_mvp", title: "The LinkedIn MVP Award", description: "Most likely to write a LinkedIn post about anything.", type: "single" },
  { id: "class_act", title: "The Class Act Award", description: "The epitome of class and grace.", type: "single" },
  { id: "sunshine", title: "The Sunshine Award", description: "Most likely to brighten up your day.", type: "single" },
  { id: "connector", title: "The Connector Award", description: "Has the biggest network and is always making introductions.", type: "single" },
  { id: "uniter", title: "The Uniter Award", description: "Most likely to bring the class together again 20 years from now.", type: "single" },
  { id: "do_it_all", title: "The Do-It-All Award", description: "Does it all and makes you wonder whether they have the same 24 hours in a day that you do.", type: "single" },
  { id: "best_dressed_male", title: "Put That Shit On Award \u2014 Best Dressed (Male-Presenting)", description: "Best dressed, male-presenting.", type: "single" },
  { id: "best_dressed_female", title: "Put That Shit On Award \u2014 Best Dressed (Female-Presenting)", description: "Best dressed, female-presenting.", type: "single" },
  { id: "seen_every_function_male", title: "The \u201CSeen at Every Function\u201D Award \u2014 Best Man", description: "Always outside, always present.", type: "single" },
  { id: "seen_every_function_female", title: "The \u201CSeen at Every Function\u201D Award \u2014 Best Woman", description: "Always outside, always present.", type: "single" },
  { id: "calendar_booked", title: "The Calendar Is Booked Award", description: "Hardest person to schedule.", type: "single" },
  { id: "group_chat_carry", title: "The Group Chat Carry Award", description: "Keeps the chat alive.", type: "single" },
  { id: "plot_twist", title: "The Plot Twist Award", description: "Most unexpected post-MBA path.", type: "single" },
  { id: "lowkey_legend", title: "The Lowkey Legend Award", description: "Quiet but iconic.", type: "single" },
  { id: "memory_keeper", title: "The Memory Keeper Award", description: "Always documenting the moment.", type: "single" },
  { id: "delayed_reply", title: "The Delayed Reply, Real Love Award", description: "Takes forever to text back but always comes through.", type: "single" },
  { id: "main_character", title: "The Main Character Award", description: "You notice when they arrive.", type: "single" },
  { id: "future_billionaire", title: "The Future Billionaire Award", description: "We expect great wealth.", type: "single" },
  { id: "podcast_energy_male", title: "The Podcast Energy Award \u2014 Best Man", description: "Could definitely have a podcast.", type: "single" },
  { id: "podcast_energy_female", title: "The Podcast Energy Award \u2014 Best Woman", description: "Could definitely have a podcast.", type: "single" },
  { id: "missed_connection", title: "The Missed Connection Award", description: "The couple that could\u2019ve been.", type: "duo" },
  { id: "plug", title: "The Plug Award", description: "Always knows the move, the resource, and the right person to call.", type: "single" },
  { id: "class_clown", title: "The Class Clown Award", description: "Always brings the jokes.", type: "single" },
  { id: "world_traveler", title: "The World Traveler Award", description: "Always in a different city or country.", type: "single" },
  { id: "dynamic_duo", title: "The Dynamic Duo Award", description: "An iconic friendship.", type: "duo" },
  { id: "best_smile", title: "The Best Smile Award", description: "Self-explanatory.", type: "single" },
  { id: "attendance_acrobat", title: "The Attendance Acrobat Award", description: "Most likely to ask for the code.", type: "single" },
  { id: "huntsman_frequent_flyer", title: "The Huntsman Frequent Flyer Award", description: "Might actually live in the MBA Lounge.", type: "single" },
  { id: "palmer_scholar", title: "The Palmer Scholar Energy Award", description: "Always academically on point.", type: "single" },
];
